const data = [
   {
      id: 76730,
      type: "headphones",
      name: "XX99 Mark I Headphone",
      desc: "As the gold standard for headphones, the classic XX99 Mark I offers detailed and accurate audio reproduction for audiophiles, mixing engineers, and music aficionados alike in studios and on the go.",
      price: "1750",
      imagePathDesktop: "/images/category-headphones/desktop/image-xx99-mark-one.jpg",
      imagePathMobile: "/images/category-headphones/mobile/image-xx99-mark-one.jpg",
      imagePathTablet: "/images/category-headphones/tablet/image-xx99-mark-one.jpg",
      imagePathShopShared: "/images/shared/desktop/image-headphones.png",
   },
   {
      id: 76731,
      type: "headphones",
      name: "XX99 Mark II Headphone",
      desc: "The new XX99 Mark II headphones is the pinnacle of pristine audio. It redefines your premium headphone experience by reproducing the balanced depth and precision of studio-quality sound.",
      price: "1800",
      imagePathDesktop: "/images/category-headphones/desktop/image-xx99-mark-two.jpg",
      imagePathMobile: "/images/category-headphones/mobile/image-xx99-mark-two.jpg",
      imagePathTablet: "/images/category-headphones/tablet/image-xx99-mark-two.jpg",
   },
   {
      id: 76732,
      type: "headphones",
      name: "XX59 Headphones",
      desc: "Enjoy your audio almost anywhere and customize it to your specific tastes with the XX59 headphones. The stylish yet durable versatile wireless headset is a brilliant companion at home or on the move.",
      price: "1600",
      imagePathDesktop: "/images/category-headphones/desktop/image-xx59.jpg",
      imagePathMobile: "/images/category-headphones/mobile/image-xx59.jpg",
      imagePathTablet: "/images/category-headphones/tablet/image-xx59.jpg",
   },
   {
      id: 76733,
      type: "earphones",
      name: "YX1 WIRELESS EARPHONES",
      desc: "Tailor your listening experience with bespoke dynamic drivers from the new YX1 Wireless Earphones. Enjoy incredible high-fidelity sound even in noisy environments with its active noise cancellation feature.",
      price: "1500",
      imagePathDesktop: "/images/category-earphones/desktop/image-yx1-earphones.jpg",
      imagePathMobile: "/images/category-earphones/mobile/image-yx1-earphones.jpg",
      imagePathTablet: "/images/category-earphones/tablet/image-yx1-earphones.jpg",
      imagePathShopShared: "/images/shared/desktop/image-earphones.png",
   },
   {
      id: 76734,
      type: "speakers",
      name: "ZX9 speaker",
      desc: "Stream high quality sound wirelessly with minimal to no loss. The ZX7 speaker uses high-end audiophile components that represents the top of the line powered speakers for home or studio use.",
      price: "1600",
      imagePathDesktop: "/images/category-speakers/desktop/image-zx9.jpg",
      imagePathMobile: "/images/category-speakers/mobile/image-zx9.jpg",
      imagePathTablet: "/images/category-speakers/tablet/image-zx9.jpg",
      imagePathShopShared: "/images/shared/desktop/image-speakers.png",
   },
   {
      id: 76735,
      type: "speakers",
      name: "ZX7 speaker",
      desc: "Upgrade your sound system with the all new ZX9 active speaker. It’s a bookshelf speaker system that offers truly wireless connectivity -- creating new possibilities for more pleasing and practical audio setups.",
      price: "1800",
      imagePathDesktop: "/images/category-speakers/desktop/image-zx7.jpg",
      imagePathMobile: "/images/category-speakers/mobile/image-zx7.jpg",
      imagePathTablet: "/images/category-speakers/tablet/image-zx7.jpg",
   },
];

export default data;
